### ISSUE TITLE
Agregar popUpTo a la barra de navegación

### ISSUE THREAD

**Issue by Mj-br** [timacosta/PokeArch#76]

**Comment by Mj-br** [comment]
Al navegar de una feature a otra se va acumulando en el backstack todo.

Desde una feature si queremos ir hacia atrás lo mejor sería ir a home directamente? O quizá que se mantenga en la misma pantalla?

Y luego desde la home añadir un backHandler para preguntarle al usuario a través de un dialog si quiere salir de la aplicación.

**Comment by timacosta** [comment]
Option 1. Arreglar y descomentar esto. Con ello podemos evitar que usando la android navigation bar. Esta seria la opción ideal 
```
private fun NavOptionsBuilder.navigateToTopLevelDestination(navController: NavController) {
    navController.graph.startDestinationRoute?.let { route ->
        popUpTo(route) {
            saveState = true
        }
    }
    launchSingleTop = true
    restoreState = true
}
```

Option 2. Salirse de la app con o sin dialog previo. Esto es consistent con el funcionamiento antes de Android 11. De hecho, tenemos una navegación relativamente simple y casi todo son top navigations. Entonces volver a la home con el back button de la android navigation bar, no veo que aporte mucho. Pero lo podemos probar. Buen punto @Mj-br 

**System behavior on Android 11 and lower**
The system finishes the activity.
**System behavior on Android 12 and higher**
The system moves the activity and its task to the background instead of finishing the activity. This behavior matches the default system behavior when navigating out of an app using the Home button or gesture.

**Comment by Mj-br** [comment]
Resuelto
